[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
opentelemetry = "0.16"
opentelemetry-otlp = "0.12"
opentelemetry-jaeger = "0.16"
tonic = "0.4"

[[bin]]
name = "cxx"
path = "src/cxx.rs"